version: '3'

services:
  item-app:
    image: ghcr.io/kusumaningrat/item-app:v1
    container_name: item-app
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dicoding
      MONGO_INITDB_ROOT_PASSWORD: item-db
    networks:
      - item
    ports:
      - 80:8080
    volumes:
      - app-db:/data/db
    depends_on:
      - item-db

  item-db:
    image: mongo:3
    container_name: item-db
    restart: always
    networks:
      - item
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: dicoding
      MONGO_INITDB_ROOT_PASSWORD: item-db
    volumes:
      - app-db:/data/db

networks:
  item:
    driver: bridge

volumes:
  app-db:
