---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    name: order-service
spec:
  type: NodePort
  selector:
    name: order-service
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      name: order
  template:
    metadata:
      labels:
        name: order
    spec:
      containers:
        - name: order
          image: ghcr.io/kusumaningrat/order-service
          env:
            - name: AMPQ_URL
              value: http://192.168.49.2:30000
          port:
            containerPort: 3000
