---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  labels:
    name: shipping-service
spec:
  type: NodePort
  selector:
    name: shipping-service
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    name: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      name: shipping
  template:
    metadata:
      labels:
        name: shipping
    spec:
      containers:
        - name: shipping
          image: ghcr.io/kusumaningrat/shipping-service
          env:
            - name: AMPQ_URL
              value: http://192.168.49.2:30001
          port:
            containerPort: 3001
